In [1]:
import torch
from circuits import Circuit,Kinds
from learn import Trainer
from data import Data

In [2]:
# Get cpu or gpu device for training.
# device = "cuda" if torch.cuda.is_available() else "cpu"
device = "cpu"
print(f"Using {device} device")

# torch.autograd.set_detect_anomaly(True)
torch.set_printoptions(precision=3, linewidth=200)

Using cpu device


In [3]:
vr = Circuit()
vr.ring(Kinds.IVS,Kinds.R,2)
vr.elements[0].attr = 1e2
vr.elements[-1].v = 1

In [4]:
data = Data(vr)
trainer = Trainer(data)

0.001


c:\Users\terry\OneDrive\Documents\GitHub\side_circuit\ml\circuits.py:104: FutureWarning: incidence_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  M_scipy = nx.incidence_matrix(G=self.nx_graph(),oriented=True)


In [5]:
trainer.run(1000, 1e-5, 10-15)

(tensor([[-41.029],
         [ 41.029],
         [ 41.029]], grad_fn=<MulBackward0>),
 tensor([[100.000],
         [ 99.000],
         [  1.000]], grad_fn=<MulBackward0>),
 tensor([1.000e+02, 2.413e+00, 2.437e-02], grad_fn=<MulBackward0>),
 tensor(6.647e-13, grad_fn=<MseLossBackward0>),
 209)