In [6]:
import torch
from circuits import Circuit,Kinds
from learn import Trainer
from data import Data

In [7]:
# Get cpu or gpu device for training.
# device = "cuda" if torch.cuda.is_available() else "cpu"
device = "cpu"
print(f"Using {device} device")

# torch.autograd.set_detect_anomaly(True)
torch.set_printoptions(precision=3, linewidth=200)

Using cpu device


In [8]:
vr = Circuit()
vr.ring(Kinds.IVS,Kinds.R,2)
vr.elements[0].attr = 1e2
vr.elements[-1].v = 1

In [9]:
data = Data(vr)
trainer = Trainer(data)

0.001


In [10]:
trainer.run(1000)

(tensor([[-41.029],
         [ 41.029],
         [ 41.029]], grad_fn=<MulBackward0>),
 tensor([[100.000],
         [ 99.000],
         [  1.000]], grad_fn=<MulBackward0>),
 tensor([1.000e+02, 2.413e+00, 2.437e-02], grad_fn=<MulBackward0>),
 tensor(0., grad_fn=<MseLossBackward0>),
 286)