In [1]:
import torch
from circuits import Circuit,Kinds
from learn import Trainer
from data import Data

In [2]:
# Get cpu or gpu device for training.
# device = "cuda" if torch.cuda.is_available() else "cpu"
device = "cpu"
print(f"Using {device} device")

# torch.autograd.set_detect_anomaly(True)
torch.set_printoptions(precision=3, linewidth=200)

Using cpu device


In [3]:
vr = Circuit()
vr.ring(Kinds.IVS,Kinds.R,2)
vr.elements[0].attr = 1e6
vr.elements[-1].i = 0.1

In [4]:
data = Data(vr)
trainer = Trainer(data, 1e-1)

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)


c:\Users\terry\OneDrive\Documents\GitHub\side_circuit\ml\circuits.py:104: FutureWarning: incidence_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  M_scipy = nx.incidence_matrix(G=self.nx_graph(),oriented=True)


In [5]:
stable_threshold = 1e-5
loss_threshold = 1e-15
i_sol,v_sol,a_sol,_,_ = trainer.run(1000, stable_threshold, loss_threshold)
vr.load(i_sol,v_sol,a_sol)
i_sol,v_sol,a_sol

threshold met, updating
reset_count = 43


(tensor([[-0.100],
         [ 0.141],
         [ 0.100]]),
 tensor([[1.000e+06],
         [1.788e-01],
         [1.000e+06]]),
 tensor([1.000e+06, 1.269e+06, 1.000e+13], grad_fn=<IndexPutBackward0>))

In [6]:
vr.elements[0].i, vr.elements[0].v, vr.elements[0].attr

(-0.10000000149011612, 1000000.0, 1000000.0)

In [7]:
vr.elements[1].i, vr.elements[1].v, vr.elements[1].attr

(0.14086748659610748, 0.17881393432617188, 1269376.875)

In [8]:
vr.elements[2].i, vr.elements[2].v, vr.elements[2].attr

(0.10000000149011612, 999999.8125, 9999997730816.0)